"""Final fail-closed approval gate for a future Monitor adapter deployment.

Unit tests can exercise the decision logic with synthetic evidence.  Production may
only create an approval from signed operational reports generated by the isolated
broker, provider account review and the integrated cross-scope test matrix.
"""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass, fields
from datetime import date, datetime, timedelta, timezone

from vrsoft_extractor.mary.monitor_egress import (
    MonitorEgressAttestation,
    egress_attested,
)
from vrsoft_extractor.mary.monitor_ephemeral import (
    EPHEMERAL_CONTRACT_VERSION,
    MAX_MONITOR_CANCEL_GRACE_SECONDS,
    MAX_MONITOR_INPUT_BYTES,
    MAX_MONITOR_OUTPUT_BYTES,
    MAX_MONITOR_OUTPUT_CHUNK_BYTES,
    MAX_MONITOR_TURN_SECONDS,
)
from vrsoft_extractor.mary.monitor_isolation import (
    MonitorIsolationAttestation,
    isolation_attested,
)
from vrsoft_extractor.mary.monitor_supply_chain import (
    MonitorSupplyChainAttestation,
    supply_chain_attested,
)


RELEASE_GATE_CONTRACT_VERSION = 1
_ATTESTATION_TOKEN = object()
_SHA256 = re.compile(r"^[0-9a-f]{64}$")
_GIT_REVISION = re.compile(r"^[0-9a-f]{40}$")
_REQUIRED_BOOLEAN_CLAIMS = (
    "actual_broker_used",
    "actual_provider_used",
    "dedicated_service_identity_verified",
    "central_directory_denials_verified",
    "provider_account_policy_verified",
    "zero_data_retention_verified",
    "telemetry_disabled_verified",
    "egress_destinations_verified",
    "payload_inventory_verified",
    "success_canaries_absent",
    "provider_error_canaries_absent",
    "cancellation_canaries_absent",
    "crash_canaries_absent",
    "restart_canaries_absent",
    "cross_user_scope_verified",
    "cross_client_scope_verified",
    "identity_tampering_denied",
    "revocation_before_delivery_verified",
    "oversized_input_denied",
    "continuous_output_bounded",
    "ignored_cancel_terminated",
    "disconnect_terminated",
    "concurrency_without_queue_verified",
    "executable_drift_denied",
    "configuration_drift_denied",
    "post_run_artifact_scan_clean",
    "regression_suite_passed",
    "vulnerability_review_passed",
    "synthetic_dataset_only",
)


class MonitorReleaseGateError(RuntimeError):
    """Closed approval failure without report or customer-data content."""

    def __init__(self, code: str) -> None:
        self.code = code
        super().__init__(code)


@dataclass(frozen=True, repr=False)
class MonitorDynamicValidationEvidence:
    """Signed report metadata for the required integrated validation matrix."""

    tested_on: date
    expires_on: date
    studio_revision: str
    report_sha256: str
    canary_set_sha256: str
    network_capture_sha256: str
    security_approval_sha256: str
    data_owner_approval_sha256: str
    operations_approval_sha256: str
    ephemeral_contract_version: int
    observed_max_input_bytes: int
    observed_max_output_bytes: int
    observed_max_output_chunk_bytes: int
    observed_turn_timeout_seconds: float
    observed_termination_grace_seconds: float
    actual_broker_used: bool
    actual_provider_used: bool
    dedicated_service_identity_verified: bool
    central_directory_denials_verified: bool
    provider_account_policy_verified: bool
    zero_data_retention_verified: bool
    telemetry_disabled_verified: bool
    egress_destinations_verified: bool
    payload_inventory_verified: bool
    success_canaries_absent: bool
    provider_error_canaries_absent: bool
    cancellation_canaries_absent: bool
    crash_canaries_absent: bool
    restart_canaries_absent: bool
    cross_user_scope_verified: bool
    cross_client_scope_verified: bool
    identity_tampering_denied: bool
    revocation_before_delivery_verified: bool
    oversized_input_denied: bool
    continuous_output_bounded: bool
    ignored_cancel_terminated: bool
    disconnect_terminated: bool
    concurrency_without_queue_verified: bool
    executable_drift_denied: bool
    configuration_drift_denied: bool
    post_run_artifact_scan_clean: bool
    regression_suite_passed: bool
    vulnerability_review_passed: bool
    synthetic_dataset_only: bool

    def __repr__(self) -> str:
        return "MonitorDynamicValidationEvidence(redacted)"


class MonitorReleaseApproval:
    """Opaque, expiring approval for future adapter startup."""

    __slots__ = (
        "contract_version",
        "egress_manifest_digest",
        "expires_on",
        "isolation_manifest_digest",
        "release_digest",
        "studio_revision",
        "supply_chain_manifest_digest",
        "_token",
    )

    def __init__(
        self,
        release_digest: str,
        studio_revision: str,
        expires_on: date,
        isolation_manifest_digest: str,
        egress_manifest_digest: str,
        supply_chain_manifest_digest: str,
        token: object,
    ) -> None:
        if token is not _ATTESTATION_TOKEN:
            raise MonitorReleaseGateError("monitor_release_approval_invalid")
        self.contract_version = RELEASE_GATE_CONTRACT_VERSION
        self.release_digest = release_digest
        self.studio_revision = studio_revision
        self.expires_on = expires_on
        self.isolation_manifest_digest = isolation_manifest_digest
        self.egress_manifest_digest = egress_manifest_digest
        self.supply_chain_manifest_digest = supply_chain_manifest_digest
        self._token = token

    def __repr__(self) -> str:
        return (
            "MonitorReleaseApproval("
            f"contract_version={self.contract_version}, "
            f"release_digest={self.release_digest!r}, "
            f"studio_revision={self.studio_revision!r}, "
            f"expires_on={self.expires_on.isoformat()!r})"
        )


def release_approved(value: object) -> bool:
    return (
        isinstance(value, MonitorReleaseApproval)
        and value.contract_version == RELEASE_GATE_CONTRACT_VERSION
        and value._token is _ATTESTATION_TOKEN
        and bool(_SHA256.fullmatch(value.release_digest))
        and bool(_GIT_REVISION.fullmatch(value.studio_revision))
        and value.expires_on >= datetime.now(timezone.utc).date()
        and bool(_SHA256.fullmatch(value.isolation_manifest_digest))
        and bool(_SHA256.fullmatch(value.egress_manifest_digest))
        and bool(_SHA256.fullmatch(value.supply_chain_manifest_digest))
    )


def approve_monitor_release(
    evidence: MonitorDynamicValidationEvidence,
    isolation: MonitorIsolationAttestation,
    egress: MonitorEgressAttestation,
    supply_chain: MonitorSupplyChainAttestation,
) -> MonitorReleaseApproval:
    """Approve only a complete, current and mutually bound operational matrix."""

    if not (
        isolation_attested(isolation)
        and egress_attested(egress)
        and supply_chain_attested(supply_chain)
    ):
        raise MonitorReleaseGateError("monitor_release_prerequisite_rejected")
    if (
        supply_chain.isolation_manifest_digest != isolation.manifest_digest
        or supply_chain.egress_manifest_digest != egress.manifest_digest
        or supply_chain.provider_version != egress.provider_version
    ):
        raise MonitorReleaseGateError("monitor_release_binding_rejected")
    if (
        evidence.studio_revision != supply_chain.studio_revision
        or not _GIT_REVISION.fullmatch(evidence.studio_revision)
    ):
        raise MonitorReleaseGateError("monitor_release_revision_rejected")
    for value in (
        evidence.report_sha256,
        evidence.canary_set_sha256,
        evidence.network_capture_sha256,
        evidence.security_approval_sha256,
        evidence.data_owner_approval_sha256,
        evidence.operations_approval_sha256,
    ):
        if not _SHA256.fullmatch(value):
            raise MonitorReleaseGateError("monitor_release_evidence_reference_rejected")

    today = datetime.now(timezone.utc).date()
    if evidence.tested_on > today or evidence.expires_on < today:
        raise MonitorReleaseGateError("monitor_release_evidence_expired")
    if evidence.expires_on < evidence.tested_on or (
        evidence.expires_on - evidence.tested_on > timedelta(days=30)
    ):
        raise MonitorReleaseGateError("monitor_release_evidence_window_rejected")
    if evidence.ephemeral_contract_version != EPHEMERAL_CONTRACT_VERSION:
        raise MonitorReleaseGateError("monitor_release_contract_rejected")
    if not (
        0 < evidence.observed_max_input_bytes <= MAX_MONITOR_INPUT_BYTES
        and 0 < evidence.observed_max_output_bytes <= MAX_MONITOR_OUTPUT_BYTES
        and 0
        < evidence.observed_max_output_chunk_bytes
        <= min(
            MAX_MONITOR_OUTPUT_CHUNK_BYTES,
            evidence.observed_max_output_bytes,
        )
        and 0 < evidence.observed_turn_timeout_seconds <= MAX_MONITOR_TURN_SECONDS
        and 0
        < evidence.observed_termination_grace_seconds
        <= MAX_MONITOR_CANCEL_GRACE_SECONDS
    ):
        raise MonitorReleaseGateError("monitor_release_limits_rejected")

    if not all(getattr(evidence, name) is True for name in _REQUIRED_BOOLEAN_CLAIMS):
        raise MonitorReleaseGateError("monitor_release_matrix_incomplete")

    digest = _release_digest(evidence, isolation, egress, supply_chain)
    return MonitorReleaseApproval(
        digest,
        evidence.studio_revision,
        evidence.expires_on,
        isolation.manifest_digest,
        egress.manifest_digest,
        supply_chain.manifest_digest,
        _ATTESTATION_TOKEN,
    )


def _release_digest(
    evidence: MonitorDynamicValidationEvidence,
    isolation: MonitorIsolationAttestation,
    egress: MonitorEgressAttestation,
    supply_chain: MonitorSupplyChainAttestation,
) -> str:
    payload = {
        field.name: (
            getattr(evidence, field.name).isoformat()
            if isinstance(getattr(evidence, field.name), date)
            else getattr(evidence, field.name)
        )
        for field in fields(evidence)
    }
    payload.update(
        {
            "egress_manifest_digest": egress.manifest_digest,
            "isolation_manifest_digest": isolation.manifest_digest,
            "supply_chain_manifest_digest": supply_chain.manifest_digest,
        }
    )
    encoded = json.dumps(payload, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(encoded).hexdigest()
